# These are supported funding model platforms


github:
 - Alia5
custom:
 - https://www.buymeacoffee.com/flatspotso7
 - https://www.paypal.com/donate/?hosted_button_id=TDKKBV7QU67L6
 - https://paypal.me/flatspotpics