name: "Create Tagged Release"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

jobs:
  gh_tagged_release:
    name: Create tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: "Create Github release (full)"
        if: ${{ !contains( github.event.inputs.release_version, '-rc' ) }}
        uses: softprops/action-gh-release@v1
        id: expander_card_release
        with:
          body: "Release version ${{ github.event.inputs.release_version }}."
          tag_name: ${{ github.event.inputs.release_version }}
          target_commitish: "master"
          draft: false
          prerelease: false
          files: dist/expander-card.js
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
